---
title: "Schedule"
---

Please read the specified sections *before* class that day.

::: {#past style="color: lightgray"}
## Week 1

#### Tue, Jan 23

-   No class

#### Thurs, Jan 25

-   Introduction to the course
-   [Course questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSdzrD35V7bkrvaTUIMUMo9nzx6e5fmzpDg6ceiYFbZOBBPuPw/viewform?usp=sf_link)
-   [Short experiment](https://smithcollege.qualtrics.com/jfe/form/SV_71nqdhEpN8frd6B)
-   Homework:
    -   HW #1a: record your name on Moodle
    -   HW #1b: CITI training
-   **Office hours**: 2:45p - 4:00p

#### Fri, Jan 26

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   Read **Stat2** Ch. 0 (PDF on Moodle)
    -   **HW #1a due today at 11:55p**

## Week 2

#### Tue, Jan 30

-   Four-step process
-   One-way ANOVA
-   Homework due today:
    -   Read **Stat2** Ch. 5.1-5.2 (Moodle)

#### Thurs, Feb 1

-   One-way ANOVA (cont.)
-   Homework due today:
    -   Read **Stat2** Ch. 5.3
-   **Office hours**: 2:45p - 4:00p

#### Fri, Feb 2

-   **Office hours**: cancelled today
-   Homework due today:
    -   **HW #1b due today at 11:55p**

## Week 3

#### Tue, Feb 6

-   Inference for ANOVA
-   Homework due today:
    -   Read **Stat2** Ch. 5.4

#### Thurs, Feb 8

-   ANOVA Conditions
-   MP1 assignment
-   Homework due today:
    -   No reading for today
-   **Office hours**: 2:45p - 4:00p

#### Fri, Feb 9

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   **HW #2 due today at 11:55p**

## Week 4

#### Tue, Feb 13

-   Transformations
-   MP1 topics
-   Homework due today:
    -   Brainstorm topics for MP1
    -   Read **Stat2** Ch. 5.5-5.6

#### Thurs, Feb 15

-   Confidence intervals and effect sizes
-   Introduction to Qualtrics
-   Homework due today:
    -   Find potential stimuli (images) for MP1
    -   Read **Stat2** 4.5 (up to, not including, example 4.10)
    -   Read **Stat2** 5.7
-   **Office hours**: 2:45p - 4:00p

#### Fri, Feb 16

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   **HW #3 due on today at 11:55p**

## Week 5

#### Tue, Feb 20

-   Multiple comparisons
-   Time to work on MP1
-   Homework due today:
    -   Work on Qualtrics survey for MP1

#### Thurs, Feb 22

-   Four basic designs
-   Homework due today:
    -   Read **Cobb** Ch. 1.1-1.3 (PDF on Moodle)
-   **Office hours**: cancelled Rally Day

#### Fri, Feb 23

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   **HW #4 due on today at 11:55p**

## Week 6

#### Tue, Feb 27

-   Blocking
-   Homework due today:
    -   Read Ch **Stat2** Ch 6.1-6.2

#### Thurs, Feb 29

-   Fitting the model for a block design
-   Homework due today:
    -   Read Ch **Stat2** Ch 6.3
-   **Office hours**: 2:45p - 4:00p

#### Fri, Mar 1

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   **MP1 Qualtrics survey due for pre-approval by 11:55p**

## Week 7

#### Tue, Mar 4

-   MP1 Data Collection Day
-   Assessing the block design

#### Thurs, Mar 7

-   Using the block design
-   Homework due today:
    -   Read Ch **Stat2** 6.4-6.5
-   **Office hours**: Cancelled today

#### Fri, Mar 8

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   **HW #5 due tonight at 11:55p**

## Week 8 - Exam 1

#### Tue, Mar 12

-   Review for Exam 1
-   Analysis of MP1 data

#### Thurs, Mar 14

-   **Time to work on Exam 1**
-   **Office hours**: 2:45p - 4:00p

#### Fri, Mar 15

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   **Exam 1 due tonight at 11:59p on Gradescope**

## Spring Break

#### Tue, Mar 19

-   No class - Spring Break

#### Thurs, Mar 21

-   No class - Spring Break

#### Fri, Mar 22

-   No class - Spring Break

## Week 10 - MP1 due

#### Tue, Mar 26

-   Interactions
-   Two-way factorial designs
-   Homework due today:
    -   Read Ch **Stat2** 7.1-7.2

#### Thurs, Mar 28

-   Fitting two-way ANOVA
-   Practice designs
-   Homework due today:
    -   Read Ch **Stat2** 7.3
-   **Office hours**: 2:45p - 4:00p

#### Fri, Mar 29

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   **Mini Project 1 due 11:59p** (upload to Moodle by Midnight)

## Week 11

#### Tue, Apr 2

-   Fitting two-way design
-   Practice designs
-   Homework due today:
    -   Read Ch **Stat2** 7.4

#### Thurs, Apr 4

-   Practice designs
-   **Office hours**: Cancelled today

#### Fri, Apr 5

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   [**HW #6 due today at 11:55p**](homework.html)

## Week 12

#### Tue, Apr 9

-   Assessing two-way design
-   MP2 work time
-   Homework due today:
    -   Read Ch **Stat2** 7.5

#### Thurs, Apr 11

-   MP2 work time
-   Homework due today:
    -   No reading
-   **Office hours**: 2:45p - 4:00p

#### Fri, Apr 12

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   [**HW #7 due today at 11:55p**](homework.html)

## Week 13

#### Tue, Apr 16

-   MP2 project work time
-   Multiple tests
-   Homework due today:
    -   Read Ch **Stat2** 8.1 - 8.2

#### Thurs, Apr 18

-   Inference Test for S Condition
-   MP2 project work time
-   Homework due today:
    -   Read Ch **Stat2** 8.6
-   **Office hours**: 2:45p - 4:00p

#### Fri, Apr 19

-   **Office hours**: 10:50-12:05p
-   Homework due today:
    -   **MP2 Pre-approval due tonight 11:55p** (upload to Moodle)

## Week 14

#### Tue, Apr 23

-   MP2 Data Collection
-   Homework due today:
    -   Read Ch **Stat2** 8.4

#### Thurs, Apr 25

-   MP2 Data Analysis
-   Repeated measures designs
-   Homework due today:
    -   Read Ch **Stat2** 8.7-8.8
-   **Office hours**: 2:45p - 4:00p

#### Fri, Apr 26

-   Homework due today:
    -   [**HW #8 due today at 9:20a**](homework.html)
-   **Office hours**: 10:50-12:05p
:::

## Week 15 - Exam 2

#### Tue, Apr 30

-   Review for Exam 2

#### Thurs, May 2

-   **Exam 2 work time**
-   **Office hours**: 2:45p - 4:00p

#### Fri, May 3

-   **Office hours**: Cancelled
    

## Finals Week - MP2 due

#### Tue, May 7

-  **Exam 2 due tonight at 11:59p** (upload to Gradescope)

#### Thurs, May 9

-   [**Extra credit HW #9 due today at 3:00p**](homework.html)
-   **MP2 due today at 11:59p** (upload to Moodle by Midnight)

#### Fri, May 10

